spring:
  application:
    name: person-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/person_service}
    username: ${DB_USERNAME:cinebase}
    password: ${DB_PASSWORD:cinebase}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  grpc:
    server:
      port: ${GRPC_PORT:9090}

server:
  port: 8082
